### ISSUE TITLE
Page offset problem with joint spreads (double page mode)

### ISSUE THREAD

**Issue by realFPS** [Snd-R/Komelia#10]
Whenever there is a joint spread in the book, the page offset becomes incorrect. I have a good way to notice this. For right to left books, the odd page number should always be on the left side and the even page number should be on right. As shown below Komelia treats the joint spread as a single page, which is not correct. Page  6 should have been displayed with 7. Because of this issue the user will have to correct the offset everytime a spread comes up.
https://github.com/user-attachments/assets/23a930bc-94af-4fec-95df-a6ad285cd441

The correct behaviour is shown below. Perfect Viewer, Mihon treat landscape pages like double page and displays the next pages correctly.
https://files.catbox.moe/6uv3r2.mp4

**Comment by Snd-R** [comment]
There was a similar discussion in discord, I'll copy the message

>I've looked into it and it doesn't play well with current implementation of offset option
I can configure it to always display two single pages after double spread but then it becomes unclear how offset option is supposed to behave
>
>Say we have original layout:
`page1;page2->page3->doublePage4->page5:page6->page7->doublePage8->page9:page10`
>
>Currently if offset option is enabled it will apply offset after every page
`page1->page2:page3->doublePage4->page5->page6:page7->doublePage8->page9->page10`
>
>If i change it to always display two pages after double spread then offset option will effectively only apply offset until first double spread is encountered
`page1->page2:page3->doublePage4->page5:page6->page7->doublePage8->page9:page10`
It will look identical to original layout after doublePage4
>
>Ideally there should be a way to enable offset so that page6:page7 are displayed at the same time and current implementation of offset option allows that but you'll have to manually enable/disable offset option.
If your book is properly laid out there should be no need to apply/disable offset more than once (depending if you do or don't have cover page) and for any odd cases you can still manually adjust offset. So i'm inclined to keep the current behavior as is
One thing I can change is remember offset reader option so you won't need to apply it every time
>>>

I'm still open to discussion about how to handle it properly

**Comment by realFPS** [comment]
The original layout that you have taken is not possible. How can there be 3 single pages between two spreads. Only even number of single pages are possible between them. 

Disregarding that, About the setup where you have chosen to display two pages after double spread with offset.

page1->page2:page3->doublePage4->page5:page6->page7->doublePage8->page9:page10

>Ideally there should be a way to enable offset so that page6:page7 are displayed at the same time

No, the above layout is correct. I think you failed to take account of the fact that doublePage is actually two pages merged into one so the pages are in right order. The bracket contains correct page no.

page1->page2:page3->doublePage4(4:5)->page5(6):page6(7)->page7(8)->doublePage8(9:10)->page9(11):page10(12)
 
Because of taking 3 pages between two spreads the last part is fucked. Correct one would be 

page1->page2:page3->doublePage4(4:5)->page5(6):page6(7)->page7(8):page8(9)->doublePage9(10:11)

Without Offset.

page1:page2->page3->doublePage4(4:5)->page5(6):page6(7)->page7(8):page8(9)->doublePage9(10:11)

**Comment by Snd-R** [comment]
Seems like I indeed failed to take into account that double spread should count as two pages.
I think I'll introduce a separate `Double page (no cover)` mode just like in Komga and keep offset parameter as a separate option
