### ISSUE TITLE
Crashed when open cbz file with avif file in it

### ISSUE THREAD

**Issue by redfieldw** [Snd-R/Komelia#12]
In order to save space, some of my comic images were converted to the AVIF format and compressed into CBZ files. They work well on the official Komga web page, but Komelia crashes immediately when opening them. 

Please considered add support to AVIF format, thank you!

**Comment by Snd-R** [comment]
Komelia already supports avif files by using libvips and dav1d decoder. 
If there's no decoder for particular image format the error will be shown in place of the image. Seems like it tried to decode the image but for some reason that caused a crash
I can't reproduce it on my machine. Can you share cbz that causes you a crash?

**Comment by Snd-R** [comment]
It's reproducible on Android only
