### ISSUE TITLE
Error when selecting Announcements on Android

### ISSUE THREAD

**Issue by Smoukus** [Snd-R/Komelia#2]
I am using latest Komelia version (v0.5.0) on Android.

When selecting Announcements in Settings, I get the following error:
![WhatsApp Image 2024-06-20 at 21 35 30](https://github.com/Snd-R/Komelia/assets/48409293/5fd7da2b-71ba-42f0-8908-6c20e7729362)

My Komga server is on my PC, and my Android phone is connected to the same network on which the server is being run at.
Komelia is successfully connected to my Komga server, and the Komga server is running at the time of error message.

Is this a bug on your end, or something that is wrong on my end?

**Comment by Snd-R** [comment]
It's seem like a problem with komga server not being able to get announcements. Probably a firewall issue
Check if you can see announcements from webui, should be the same probem there

**Comment by Snd-R** [comment]
It's most likely firewall issue on the machine where you run komga
You'll need to allow komga to make outbound requests in the firewall
