### ISSUE TITLE
Unstable mouse wheel function.

### ISSUE THREAD

**Issue by ghost** [Snd-R/Komelia#6]
I'm using version 0.7, in continuos mode it sometimes zooms in on manga pages when it should be scrolling down with the mouse wheel and can't be fixed without touching the keyboard keys, which I think is a big problem for people like me who read manga remotely with a wireless mouse.

**Comment by Snd-R** [comment]
Zoom should only happen when you have ctrl key is pressed.
There's also support for zooming gesture on touchpads but that shouldn't apply to mice.

Does this only happen with your particular mouse, can you try with another one?
Maybe some key is getting pressed by accident, can you also try scrolling with keyboard disconnected?

**Comment by Snd-R** [comment]
You can't use onnxruntime upscaling on Android version of the app
I had an idea of creating a separate upscaling service that you run on your computer and configure your android app to connect to it to upscale images.
It's something that I might implement in the future
