### ISSUE TITLE
[Feature Request]: Show series title on BookImageCard

### ISSUE THREAD

**Issue by everpcpc** [Snd-R/Komelia#8]
Similar to komga web, show

> Series Title
> Book Title
> Pages

over book tile on home page.

**Comment by Snd-R** [comment]
I agree with adding series title. It'll help with cases when it's not obvious to what series the book belongs
It also helps with distinguishing books from series cards on home screen

I'm not sure if adding page count would be useful. How important is it to know the exact page count when browsing the home screen? If user needs to know the exact page count they can go to the book screen.
There's also a consideration about limited space that the card has. Text is drawn on top of the image and not in a separate zone under image like in Komga

**Comment by everpcpc** [comment]
Sure, it's not necessary to display page count, series title would be helpful enough.
