### ISSUE TITLE
Can't get TensorRT work on Windows 10

### ISSUE THREAD

**Issue by ghost** [Snd-R/Komelia#9]
Windows 10 Version 21H2 (Build 19044.1288)
Installed CUDA 12.6 CUDNN 9.5 TensorRT 10.5.0.18
Environment setup:
![image](https://github.com/user-attachments/assets/0522b5e2-74f8-42ad-aee8-527fa49546ce)
![image](https://github.com/user-attachments/assets/89cba64e-605e-4c70-be88-2d637d108464)
![image](https://github.com/user-attachments/assets/fdf4551f-8972-4536-8134-6c45d483bad1)
log:

**Comment by Snd-R** [comment]
Did it work on version 0.9.0?

**Comment by Snd-R** [comment]
Make sure you have cuddn in your PATH
![image](https://github.com/user-attachments/assets/bb119b9d-8609-4dfa-ac01-5013b515947c)

**Comment by Snd-R** [comment]
First try downloading latest version of Microsoft Visual C++ https://learn.microsoft.com/en-us/cpp/windows/latest-supported-vc-redist?view=msvc-170#latest-microsoft-visual-c-redistributable-version

If that doesn't work then next you can try downloading https://github.com/lucasg/Dependencies and check onnxruntime_providers_tensorrt.dll file `C:\Users\user\AppData\Local\Temp\komelia\libs\onnxruntime_providers_tensorrt.dll`
It should show if there's a missing library that it can't find
